# docker-compose.yml

version: '3.8'

services:
  app:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn workshop.app:app --host 0.0.0.0'
    volumes:
      - .:/workshop
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=postgresql://fastapi_basic_project:fastapi_user@db:5432/fastapi_basic_project
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=fastapi_user
      - POSTGRES_PASSWORD=fastapi_password
      - POSTGRES_DB=fastapi_basic_project

volumes:
  postgres_data: