version: '3.6'
services:
  app:
    build: .
    volumes:
      - .:/workshop
    ports:
      - '8000:8000'

    depends_on:
      - postgres
    networks:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres
    restart: always
    user: root
    env_file:
      - database.env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - postgres

volumes:
  postgres:
    driver: local
  redis_data:

networks:
  postgres:
    driver: bridge